[package]
name = "musicus"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.33"
diesel = { version = "1.4.5", features = ["sqlite"] }
diesel_migrations = "1.4.0"
discid = "0.4.4"
fragile = "1.0.0"
futures = "0.3.6"
futures-channel = "0.3.5"
gdk = "0.13.2"
gettext-rs = "0.5.0"
gio = "0.9.1"
glib = "0.10.2"
gtk = { version = "0.9.2", features = ["v3_24"] }
gtk-macros = "0.2.0"
gstreamer = "0.16.4"
gstreamer-player = "0.16.3"
isahc = "0.9.12"
libhandy = "0.7.0"
pango = "0.9.1"
rand = "0.7.3"
secret-service = "1.1.1"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
uuid = { version = "0.8", features = ["v4"] }
