[package]
name = "musicus_editor"
version = "0.1.0"
edition = "2018"

[dependencies]
diesel = { version = "1.4.5", features = ["sqlite"] }
diesel_migrations = "1.4.0"
gio = "0.9.1"
glib = "0.10.2"
gtk = { version = "0.9.2", features = ["v3_24"] }
gtk-macros = "0.2.0"
libhandy = "0.7.0"
pango = "0.9.1"
rand = "0.7.3"
