[package]
name = "musicus"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.33"
async-trait = "0.1.42"
diesel = { version = "1.4.5", features = ["sqlite"] }
diesel_migrations = "1.4.0"
discid = "0.4.4"
fragile = "1.0.0"
futures = "0.3.6"
futures-channel = "0.3.5"
gettext-rs = "0.5.0"
gtk-macros = "0.2.0"
gstreamer = "0.16.4"
gstreamer-player = "0.16.3"
isahc = "0.9.12"
once_cell = "1.5.2"
rand = "0.7.3"
secret-service = "2.0.1"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
thiserror = "1.0.23"
uuid = { version = "0.8", features = ["v4"] }

[dependencies.gdk]
git = "https://github.com/gtk-rs/gtk4-rs/"
package = "gdk4"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs/"
features = ["v2_64"]

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs/"
features = ["v2_64"]

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk4-rs"
package = "gtk4"

[dependencies.libadwaita]
git = "https://gitlab.gnome.org/bilelmoussaoui/libadwaita-rs"
package = "libadwaita"

[dependencies.pango]
git = "https://github.com/gtk-rs/gtk-rs/"
features = ["v1_44"]
