[package]
name = "musicus_database"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "1.4.5", features = ["sqlite"] }
diesel_migrations = "1.4.0"
chrono = "0.4.19"
log = "0.4.14"
rand = "0.7.3"
thiserror = "1.0.23"
uuid = { version = "0.8", features = ["v4"] }
